'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function clone(obj) {
    if (obj instanceof Array) {
        return new Array(obj);
    }
    if (obj instanceof Map) {
        return new Map(obj);
    }
    if (obj == null || typeof obj != 'object')
        return obj;
    return JSON.parse(JSON.stringify(obj));
}

const Select = {
    Fittest,
    FittestLinear,
    FittestRandom,
    Random,
    RandomLinearRank,
    Sequential,
    Tournament2,
    Tournament3,
};
class Genetic {
    constructor(options) {
        this.stats = {};
        this.internalGenState = {}; /* Used for random linear */
        this.population = [];
        /**
         * Sort algorythm
         */
        this.optimize = (a, b) => {
            return a >= b;
        };
        /**
         * Try cross a pair or one selected phenotypes
         */
        this.tryCrossover = () => {
            const { crossoverProbablity, crossoverFunction } = this.options;
            let selected = crossoverFunction && Math.random() <= crossoverProbablity ? this.selectPair() : this.selectOne();
            if (selected.length === 2) {
                selected = crossoverFunction(selected[0], selected[1]);
            }
            return selected.map(this.tryMutate);
        };
        /**
         * Try mutate entity with optional probabilty
         */
        this.tryMutate = (entity) => {
            // applies mutation based on mutation probability
            if (this.options.mutationFunction && Math.random() <= this.options.mutateProbablity) {
                return this.options.mutationFunction(entity);
            }
            return entity;
        };
        const defaultOptions = {
            populationSize: 250,
            mutateProbablity: 0.2,
            crossoverProbablity: 0.9,
            fittestNSurvives: 1,
            select1: Select.Fittest,
            select2: Select.Tournament2,
        };
        this.options = { ...defaultOptions, ...options };
    }
    /**
     * Startup population, if not passed than will be random generated by randomFunction()
     */
    seed(entities = []) {
        this.population = entities.map((entity) => ({ fitness: null, entity }));
        // seed the population
        for (let i = 0; i < this.options.populationSize; ++i) {
            this.population.push({ fitness: null, entity: this.options.randomFunction() });
        }
    }
    best(count = 1) {
        let population = this.population;
        if (this.options.deduplicate) {
            population = this.population.filter((ph) => this.options.deduplicate(ph.entity));
        }
        return population.slice(0, count).map((ph) => ph.entity);
    }
    /**
     * Breed population with optional breed settings
     */
    breed() {
        // crossover and mutate
        const newPop = [];
        // lets the best solution fall through
        if (this.options.fittestNSurvives) {
            newPop.push(...this.cutPopulation(this.options.fittestNSurvives));
        }
        // Lenght may be change dynamically, because fittest and some pairs from crossover
        while (newPop.length < this.options.populationSize) {
            newPop.push(...this.tryCrossover().map((entity) => ({ fitness: null, entity })));
        }
        if (this.options.deduplicate) {
            this.population = this.population.filter((ph) => this.options.deduplicate(ph.entity));
            this.seed();
        }
        this.population = newPop;
    }
    /**
     * Estimate population before breeding
     */
    async estimate() {
        const { fitnessFunction } = this.options;
        // reset for each generation
        this.internalGenState = {};
        const tasks = await Promise.all(this.population.map(({ entity }) => fitnessFunction(entity)));
        for (let i = 0; i < this.population.length; i++) {
            this.population[i].fitness = tasks[i];
        }
        this.population = this.population.sort((a, b) => (this.optimize(a.fitness, b.fitness) ? -1 : 1));
        const popLen = this.population.length;
        const mean = this.getMean();
        this.stats = {
            population: this.population.length,
            maximum: this.population[0].fitness,
            minimum: this.population[popLen - 1].fitness,
            mean,
            stdev: this.getStdev(mean),
        };
    }
    /**
     * Mean deviation
     */
    getMean() {
        return this.population.reduce((a, b) => a + b.fitness, 0) / this.population.length;
    }
    /**
     * Standart deviation
     */
    getStdev(mean) {
        const { population: pop } = this;
        const l = pop.length;
        return Math.sqrt(pop.map(({ fitness }) => (fitness - mean) * (fitness - mean)).reduce((a, b) => a + b, 0) / l);
    }
    /**
     * Select one phenotype from population
     */
    selectOne() {
        const { select1 } = this.options;
        return [clone(select1.call(this, this.population))];
    }
    /**
     * Select two phenotypes from population for crossover
     */
    selectPair() {
        const { select2 } = this.options;
        return [clone(select2.call(this, this.population)), clone(select2.call(this, this.population))];
    }
    /**
     * Return population without an estimate (fitness)
     */
    cutPopulation(count) {
        return this.population.splice(0, count).map((ph) => ({ fitness: null, entity: ph.entity }));
    }
}
/** Utility */
function Tournament2(pop) {
    const n = pop.length;
    const a = pop[Math.floor(Math.random() * n)];
    const b = pop[Math.floor(Math.random() * n)];
    return this.optimize(a.fitness, b.fitness) ? a.entity : b.entity;
}
function Tournament3(pop) {
    const n = pop.length;
    const a = pop[Math.floor(Math.random() * n)];
    const b = pop[Math.floor(Math.random() * n)];
    const c = pop[Math.floor(Math.random() * n)];
    let best = this.optimize(a.fitness, b.fitness) ? a : b;
    best = this.optimize(best.fitness, c.fitness) ? best : c;
    return best.entity;
}
function Fittest(pop) {
    return pop[0].entity;
}
function FittestLinear(pop) {
    this.internalGenState['flr'] = this.internalGenState['flr'] || 0;
    return pop[this.internalGenState['flr']++].entity;
}
function FittestRandom(pop) {
    return pop[Math.floor(Math.random() * 11)].entity;
}
function Random(pop) {
    return pop[Math.floor(Math.random() * pop.length)].entity;
}
function RandomLinearRank(pop) {
    this.internalGenState['rlr'] = this.internalGenState['rlr'] || 0;
    return pop[Math.floor(Math.random() * Math.min(pop.length, this.internalGenState['rlr']++))].entity;
}
function Sequential(pop) {
    this.internalGenState['seq'] = this.internalGenState['seq'] || 0;
    return pop[this.internalGenState['seq']++ % pop.length].entity;
}

exports.Genetic = Genetic;
exports.Select = Select;
